### DISCUSSION TITLE
deploy the Blazor web with https

### DISCUSSION THREAD

**Discussion by luklapse** [linkdotnet/Blog#133] [Q&A]
Hello, I really like the layout of this Blog website, and its features are comprehensive enough to meet my needs. 
Personally, I have worked with C# but not with ASP.NET, and Blazor's framework is very complex to me.
Local testing went smoothly, but I encountered some trouble with https when deploying to the server.
 I have used Google to search for answers to the problem, but it seems that there is no good answer. 
If I use nginx reverse proxy for https, Blazor will try to redirect https, but if only http is used, the authorization part will not be able to log in. 
How should I deploy it, if possible using docker would be even better.

**Comment by linkdotnet** [comment]
Hey, thanks for the supportive words. As I don't use the Blog with a docker container, let us figure this one out together.
The docker file itself can be created (I will try a rough outline a bit later). Where did you deploy your application to? You said that everything besides the login worked. As the authentication (when deployed) is done via Auth0, did you setup the account details in the appsettings.config as well as on the Auth0 website?

Regarding nginx and Blazor, I can only refer to [this](https://www.indie-dev.at/2021/07/18/nginx-blazor-server-side/) article, as I don't use a reverse proxy in between.

Here a rough sketch for a dockerfile you could use:

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src/LinkDotNet.Blog.Web
COPY ["LinkDotNet.Blog.Web.csproj", "."]
RUN dotnet restore "LinkDotNet.Blog.Web.csproj"
COPY . .
RUN dotnet build "LinkDotNet.Blog.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LinkDotNet.Blog.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LinkDotNet.Blog.Web.dll"]
```

Then you should be able to create the container via:
```bash
docker build -t LinkDotNet.Blog.Web .
```

For this to work you would still need a storage provider somewhere (SQL, RavenDb, ...). You could also use an image where there is already an SQL instance available.

**Reply by luklapse** [reply]
Thank you for coming back , I continued to research this issue
1. For nginx reverse proxy, to make the Blazor service only handle http requests, you can follow the provided link to configure it. However, if it is not successful, it may be because of a redirect to https, or a problem with the Auth0 setting causing a login error with a mismatch in callback urls. In the Auth0 web setting, the callback urls are set to https:DOMAIN_NAME/callback and http:DOMAIN_NAME/callback.I don't know how to fix them since I'm not familiar with Blazor's framework

2. To avoid using nginx, Blazor service must handle https requests.The Kestrel web server needs to be provided with an SSL certificate in PFX format, and the password must be set.. According to the [ASP.NET documentation](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-7.0&tabs=visual-studio), you can use the `ASPNETCORE_Kestrel__Certificates__Default__Path` and `ASPNETCORE_Kestrel__Certificates__Default__Password` environment variables to set them, as well as the `ASPNETCORE_URLS` environment variable to specify the URLs you want to listen to. It seems you can also use the appsettings.json file to set these values, but using Docker may be more universal.

3. Here is the file I used,
The Docker configuration(The dockerfile you provided doesn't work very well,and I modified it):
```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src/LinkDotNet.Blog.Web
COPY ./ /
RUN dotnet restore "LinkDotNet.Blog.Web.csproj"
RUN dotnet build "LinkDotNet.Blog.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LinkDotNet.Blog.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LinkDotNet.Blog.Web.dll"]
```
docker-compose file
```yml
services:
  dotnet:
    image: linkdotnet.blog.web
    build: ./
    container_name: dotnetBlog
    ports:
      - 1234:1234 #You can modify the port you want
      - 1235:1235
    volumes:
      - /root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      - ./Blog.db:/App/Blog.db #SQlite datebase
      - /root/Project/BlazorBlog/aspnetapp.pfx:/App/aspnetapp.pfx #ssl certificate
    environment:
      - ASPNETCORE_URLS=http://+:1234;https://+:1235
      - ASPNETCORE_HTTPS_PORT=1235
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/App/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Production
```
Both files are placed in the root directory of the project, not in a subfolder.
`docker compose up -d` 
The rest doesn't need to be modified, it works well. I have successfully deployed it to [my website](https://luckluck.club:1235/)
